config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("myhome_dj.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("myfinances/", include("myfinances.urls", namespace="myfinances")),
    path("mypersonals/", include("mypersonals.urls", namespace="mypersonals"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

myfinances/urls.py
from django.urls import path
from myfinances.views import index, expensehome, addexpense, incomeshome, addincome

app_name = "myfinances"

urlpatterns = [
    path("", view=index, name="index"),
    # expenses
    path("expensehome", view=expensehome, name="expensehome"),
    path("addexpense", view=addexpense, name="addexpense"),
    # incomes
    path("incomeshome", view=incomeshome, name="incomeshome"),
    path("addincome", view=addincome, name="addincome"),
]

myfinances/models.py
from django.db import models
from datetime import datetime
from myhome_dj.users.models import User

# Create your models here.
class Expenses(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(null=False, max_length=150)
    TYPE_CHOICES = [
        ('food', 'Food'),
        ('entertainment', 'Entertainment'),
        ('living', 'Living')        
    ]
    type = models.CharField(max_length=20, choices=TYPE_CHOICES, default='food')
    amount = models.FloatField(max_length=10, null=False)
    details = models.TextField(max_length=256, null=True)
    dateOfExpense = models.DateTimeField(default=datetime.now, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Files(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(null=False, max_length=150)
    type = models.CharField(null=True, max_length=50)
    dateOfUpload = models.DateTimeField(default=datetime.now, null=False)
    contents = models.BinaryField(null=True)
    size = models.FloatField(default=0)
    expense = models.ForeignKey(Expenses, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class DjFiles(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.FileField()

    def __str__(self):
        return self.name

myfinances/forms.py
from myfinances.models import Expenses, Files
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, Field, Div

class DateInput(forms.DateInput):
    input_type = 'date'

class ExpenseForm(forms.ModelForm):

    bill = forms.FileField()

    class Meta:
        model = Expenses
        widgets = {
            'dateOfExpense': DateInput,
            'details': forms.Textarea(attrs={'rows':3})
        }
        fields = ['name', 'type', 'amount', 'details', 'dateOfExpense']

class SearchExpenseForm(forms.Form):

    freq_choices = (('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly'))
    frequency = forms.ChoiceField(choices=freq_choices)
    date = forms.DateField(widget=DateInput)

    FormHelper.layout = Layout(
        Field('frequency', css_class="custom-select btn-secondary"),
        Field('date', css_class="form-control")
    )

    FormHelper.layout = Layout(
    Div(
        Field('name'), css_class="my_fancy_class_name"
    ),
    Field('description'),
)

myfinances/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.http import HttpResponse
from django.utils.translation import ugettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView
from myfinances import forms
from myfinances.models import Files, Expenses
from django.conf import settings
from django.db.models.functions import ExtractYear, ExtractMonth, ExtractDay
import datetime


def index(request):

    return render(request, 'index.html')


def expensehome(request):

    if not request.user.is_authenticated:
        return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))

    else:
        user_id = request.user.id
        today = datetime.date.today()
        expenses = Expenses.objects.filter(user_id=user_id)

        expenses_filtered = Expenses.objects.filter(user_id=user_id, dateOfExpense = today)

        form = forms.SearchExpenseForm()

        if request.method == 'POST':
            form = forms.SearchExpenseForm(request.POST)

            if form.is_valid():
                print('POST in expensehome')
                frequency = form.cleaned_data['frequency']
                selecteddate = form.cleaned_data['date']
                print(f'Frequency selected: {frequency}')
                print(f'Date selected: {selecteddate}')
                print(request.user.id)
                today = datetime.date.today()    

                if frequency in 'yearly':
                    expenses_filtered = expenses.filter(dateOfExpense__year = selecteddate.year)
                elif frequency in 'monthly':
                    expenses_filtered = expenses.filter(dateOfExpense__month = selecteddate.month)
                elif frequency in 'daily':
                    expenses_filtered = expenses.filter(dateOfExpense__day = selecteddate.day).all()
                else:
                    expenses_filtered = expenses.filter(Expenses.dateOfExpense == today)

        return render(request, 'expenses/expenseshome.html', {'form': form, 'expenses': expenses_filtered})


def addexpense(request):

    if not request.user.is_authenticated:
        return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))

    else:
        today = datetime.date.today()
        user_id = request.user.id
        expenses = Expenses.objects.filter(user_id = user_id, dateOfExpense = today)

        form = forms.ExpenseForm()

        if request.method == 'POST':
            form = forms.ExpenseForm(request.POST, request.FILES)

            if form.is_valid():
                print('POST')
                print(form.cleaned_data['name'])
                Files.name = request.FILES['bill']
                form.instance.user = request.user
                form.save(commit=True)
                print(request.FILES['bill'])

        return render(request, 'expenses/addexpense.html', {'form': form, 'expenses': expenses})


# def deleteexpense(request, expense_id):

#     if not request.user.is_authenticated:
#         print('User tried accessing financials.delete and not authorized')
#         return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))

#     else:
#         print(f'User authenticated {request.user.username} and accessed delete in expenses')
#         print(f'Deleting expense id {expense_id}')
#         expense = Expenses.query.get_or_404(expense_id)
#         db.session.delete(expense)
#         if files:
#             print(f'File {files.name} attached to expense, deleting it')
#             db.session.delete(files)
#         db.session.commit()

#         return redirect(request.referrer)


def incomeshome(request):

    return render(request, 'incomes/incomeshome.html')


def addincome(request):

    return render(request, 'incomes/addincome.html')

# Create your views here.

myfinances/templates/expenses/addexpense.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="jumbotron">
  <h1 class="display-4">Add Expense</h1>
  <p class="lead">Use this page to add expense for the date.</p>
  <hr class="my-4" />
  <p>
    To add logs, click on Add + and enter your details
    today.
  </p>
  <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#addExpenseModal">
    Add Expense
  </button>
  <a class="btn btn-secondary btn-lg" href="{% url 'myfinances:expensehome' %}" role="button">View Expenses</a>

</div>

<div class="row justify-content-center">
  <div class="col-10">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Date</th>
          <th scope="col">Name</th>
          <th scope="col">Type</th>
          <th scope="col">Amount</th>
          <th scope="col">Details</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        {% for expense in expenses %}
        <tr>
          <th scope="row"><a href="">{{ forloop.counter }}</a></th>
          <td>{{ expense.date_of_expense|date:"d M Y" }}</td>
          <td>{{ expense.name }}</td>
          <td>{{ expense.type }}</td>
          <td>{{ expense.amount }}</td>
          <td>{{ expense.details }}</td>
          <td><a class="btn btn-danger btn-sm" href="" role="button">Delete</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="addExpenseModal" data-backdrop="static" tabindex="-1" role="dialog"
  aria-labelledby="addExpenseModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addExpenseModalLabel">Add Expense</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="POST" enctype="multipart/form-data">
        <div class="modal-body">
          {% csrf_token %}
          {{ form|crispy }}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">
            Close
          </button>
          <button class="btn btn-primary" type="Submit">
            Add
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

myfinances/templates/expenses/expenseshome.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static i18n %}
{% block content %}
<div class="jumbotron">
  <h1 class="display-4">Expenses Home</h1>
  <p class="lead">Use this page to add, delete and view expenses</p>
  <hr class="my-4">
  <p>Select Date to view Logs for a particular date or month or year</p>
  <a class="btn btn-primary btn-lg" href="{% url 'myfinances:addexpense' %}">{% trans "Add Expense" %}</a>
  <a class="btn btn-secondary btn-lg " href="{% url 'myfinances:expensehome' %}">{% trans "Dashboard" %}</a>
</div>

<div class="card text-center" style="width: auto; border: none;">
  <div class="card-body">
    <form class="form-inline" method="post">
      <div class="form-group mb-2">
        {% csrf_token %}
        {{ form|crispy }}
      </div>
      <button type="submit" class="btn btn-secondary mx-sm-3 mb-2">Search</button>
    </form>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-10">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Date</th>
          <th scope="col">Name</th>
          <th scope="col">Type</th>
          <th scope="col">Amount</th>
          <th scope="col">Details</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        {% for expense in expenses %}
        <tr>
          <th scope="row"><a href="">{{ forloop.counter }}</a></th>
          <td>{{ expense.date_of_expense|date:"d M Y" }}</td>
          <td>{{ expense.name }}</td>
          <td>{{ expense.type }}</td>
          <td>{{ expense.amount }}</td>
          <td>{{ expense.details }}</td>
          <td><a class="btn btn-danger btn-sm" href="" role="button">Delete</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}